Update application.html
opportunity-hack/quill pull request #18
Opened 2024-08-17 07:19 UTC by Ruchi-here

Update application.html based on MLH guidelines

2024-08-18 05:23 UTC, gregv commented
@AndrewHUNGNguyen  - heads up on this one - it adds a few more fields to the database that we need for our MLH sponsorship

2024-08-19 06:12 UTC, Ruchi-here commented
![image](https://github.com/user-attachments/assets/234d28cf-71bd-4b33-a682-e9aa33e6e878)
![image](https://github.com/user-attachments/assets/2f9782ec-252a-44b0-84e4-250864bb36f8)
![image](https://github.com/user-attachments/assets/fe9bf8d6-135a-40ff-b2cf-4de4f83cd014)
![image](https://github.com/user-attachments/assets/c0842778-8c7f-4d77-8f81-c30fa9cc8270)
![image](https://github.com/user-attachments/assets/aeb5e6a6-1b05-4305-92c6-d876c2896001)

2024-08-19 06:17 UTC, Ruchi-here commented
@gregv @AndrewHUNGNguyen if we are changing the main database for storing the first and last name then we have to ensure on the confirmation page that only the first and last name from the main database is being used for confirming the name instead of the existing one

2024-08-23 07:54 UTC, AndrewHUNGNguyen commented
@gregv and @Ruchi-here I am so sorry that I didn't know that I was requested to review this PR. 

As long as this PR contains all of the required fields of a MLH form, I can trust that this will work. 

However, the way all the option values for **countries** and **MLH recognized schools** are being stored in this file is excessive. When it comes to large numbers of dropdown options, we should consider storing in a .csv or .json file or database so that the html file is easier to read and maintain.

2024-08-23 21:39 UTC, AndrewHUNGNguyen requested changes

2024-08-23 21:39 UTC, AndrewHUNGNguyen commented on app/client/views/application/application.html
> +                <select name="school" ng-model="user.profile.school">
The original application file gets all of its dropdowns from a csv file located in [app/client/assets](https://github.com/opportunity-hack/quill/blob/master/app/client/assets/schools.csv) folder that applicationCtrl.js uses and parses School names from. Therefore you can update this csv file to contain all MLH-recognized schools.

2024-08-23 21:39 UTC, AndrewHUNGNguyen commented on app/client/views/application/application.html
> +            <label>Country of Residence</label>
Apply the same logic that is being done for rendering the schools by putting all countries into a csv file and having a function that will parse all these countries as drop-down options.

2024-09-27 17:52 UTC, gregv reviewed
We want to keep Name, Age, Level of Study (and not School and not Country of Residence)

2024-09-27 17:52 UTC, closed without merging